#include <iostream>
#include <stdio.h> 
#include <cstdlib>
#include <string>
#include <conio.h>

int outro() {
	std::cout << "Knowing he was potentially facing the death penalty and wanting to avoid that todd told police after he had confessed to these murders that he could actually confess to even more murders and if he did could they take the death penalty off the table and so the police ultimately would agree and todd would tell them that back in 2003 he had walked into a motorbike shop and killed four of their staff members. Apparently a couple of days earlier they had offended him in some way. He had gone in there and they had kind of made some snide remark about how he was bad at riding motorcycles it was kind of in good fun it was not meant to be very mean but todd had taken it as an absolute offense and he could not stand for it and so literally in broad daylight he had walked back into the store and gunned all of them down. Once they were all down he had walked by each of them and put an additional round into each of their heads. As todd is telling the police this terrible story hes totally nonchalant about it. He's laughing about it and he's even bragging to police that they would be proud of him at how quickly he cleared the superbike shop meaning how quickly he got in there and killed everyone inside. That somehow because police officers used weapons too they would appreciate how efficient he was. These four murders would be the only additional murders todd would confess to and they would be enough to take the death penalty off the table. But its believed todd had killed more people. In fact he had blatantly admitted to kayla when she was in captivity that his body count was in the high two digits and most likely he was telling her this because he planned on killing her before she could ever escape and tell anyone. Of course she was rescued and so the world now knows. However if todd never confesses to any more murders there's a very good chance we will never know about them.\n\nOne of the more disturbing aspect of this case is after it became public that todd kohlhepp was the killer someone discovered that an anonymous account was doing all these product reviews on amazon and this anonymous account was todd kohlhepp. The products he was reviewing were things like knives and shovels and chainsaws and the reviews literally were about how he planned on using these tools to kill people or they were how he had used these tools to kill people or how he had disposed of bodies. And then there was also a couple of reviews of padlocks and one of the reviews said he had five of them on a shipping container and so now the shipping container was just like hotel california. Hotel california is the famous song by the band 'the eagles' and in this song the famous line is you can check in anytime you like but you can never leave.\n\nTodd was ultimately sentenced to seven consecutive life sentences which means he'll spend the rest of his life in prison";

return 0;
	
	
}
